#!/bin/sh
asuser="$1"
extra="$2"

[ -z "$asuser" ] && asuser="$(whoami)"

installpath="$(dirname "$0")/.."
WD="$(pwd)"
cd "${installpath}"
installpath="$(pwd)"

git submodule init
git submodule update -f
echo "Installing in [${installpath}] as user [${asuser}]"
for scriptname in __tools__/bootstrap.d/*.sh ; do
    echo "execute [${scriptname}]"
    bash "$scriptname" "$installpath" "$asuser" "$extra"
done
cd "${WD}"
echo "Installation in [$installpath] done"
exit 0

