#!/bin/sh
asuser="$1"
extra="$2"

installpath="$(dirname "$0")/.."
WD="$(pwd)"
installpath="$(pwd)"

[ -z "$asuser" ] && asuser="$(whoami)"

cd "$installpath" && for scriptname in __tools__/bootstrap.d/*.sh ; do
    echo "execute [${scriptname}]"
    bash "$scriptname" "$installpath" "$asuser" "$extra"
done
cd "${WD}"
echo "Installation in [$installpath] done"
exit 0

